#!/usr/bin/env python3
"""Download static Street View images for historical pano IDs listed in a CSV."""

from __future__ import annotations

import argparse
import csv
import math
import os
import sys
import time
from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parents[1]
SRC_DIR = PROJECT_DIR / "src"
sys.path.insert(0, str(SRC_DIR))

from streetview import get_streetview


def load_dotenv(env_path: Path) -> None:
    if not env_path.exists():
        return
    for line in env_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip())


def bearing_deg(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    phi1 = math.radians(lat1)
    phi2 = math.radians(lat2)
    delta_lon = math.radians(lon2 - lon1)
    x = math.sin(delta_lon) * math.cos(phi2)
    y = math.cos(phi1) * math.sin(phi2) - math.sin(phi1) * math.cos(phi2) * math.cos(delta_lon)
    return (math.degrees(math.atan2(x, y)) + 360.0) % 360.0


def source_sort_key(source_index: str) -> tuple[int, str]:
    try:
        return (int(source_index), source_index)
    except ValueError:
        return (10**9, source_index)


def build_route_headings(rows: list[dict[str, str]]) -> dict[str, int]:
    coords_by_source: dict[str, tuple[float, float]] = {}
    for row in rows:
        source_index = row.get("source_index", "")
        if not source_index or source_index in coords_by_source:
            continue
        coords_by_source[source_index] = (
            float(row["source_lat"]),
            float(row["source_lon"]),
        )

    ordered_sources = sorted(coords_by_source, key=source_sort_key)
    headings: dict[str, int] = {}
    for i, source_index in enumerate(ordered_sources):
        if len(ordered_sources) == 1:
            headings[source_index] = 0
            continue

        next_i = i + 1 if i < len(ordered_sources) - 1 else i
        prev_i = i - 1 if i == len(ordered_sources) - 1 else i
        start_source = ordered_sources[prev_i]
        end_source = ordered_sources[next_i]
        lat1, lon1 = coords_by_source[start_source]
        lat2, lon2 = coords_by_source[end_source]
        headings[source_index] = int(round(bearing_deg(lat1, lon1, lat2, lon2))) % 360
    return headings


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Download Google Street View static images from historical_metadata.csv."
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=PROJECT_DIR / "outputs" / "from_route_metadata" / "historical_metadata.csv",
        help="Input CSV generated by historical_from_csv.py.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=PROJECT_DIR / "outputs" / "from_route_metadata" / "mixvpr_dataset_by_date",
        help="Output directory for downloaded JPG images.",
    )
    parser.add_argument(
        "--api-key",
        default="",
        help="Google Maps API key. Defaults to GOOGLE_MAPS_API_KEY from .env/environment.",
    )
    parser.add_argument("--limit", type=int, default=5, help="Maximum images to download. 0 means all.")
    parser.add_argument(
        "--candidate-rank",
        default="0",
        help="Candidate rank to download, or 'all' for all candidates.",
    )
    parser.add_argument("--width", type=int, default=640, help="Image width.")
    parser.add_argument("--height", type=int, default=640, help="Image height.")
    parser.add_argument("--fov", type=int, default=100, help="Field of view.")
    parser.add_argument(
        "--pitch",
        type=int,
        default=0,
        help="Pitch angle. 0 looks horizontally.",
    )
    parser.add_argument(
        "--heading-source",
        choices=("route", "historical", "zero"),
        default="route",
        help="route follows the route direction, historical uses Google's pano heading, zero forces heading=0.",
    )
    parser.add_argument(
        "--flat",
        action="store_true",
        help="Do not create date subdirectories. By default images are stored by YYYY-MM date.",
    )
    parser.add_argument("--sleep", type=float, default=0.2, help="Delay between requests.")
    return parser.parse_args()


def main() -> int:
    load_dotenv(PROJECT_DIR / ".env")
    args = parse_args()
    api_key = args.api_key or os.environ.get("GOOGLE_MAPS_API_KEY", "")
    if not api_key:
        raise SystemExit("Missing API key. Set GOOGLE_MAPS_API_KEY in .env or pass --api-key.")

    args.output_dir.mkdir(parents=True, exist_ok=True)

    with args.input.open(newline="", encoding="utf-8") as f:
        all_rows = [
            row
            for row in csv.DictReader(f)
            if row.get("search_status") == "ok" and row.get("historical_pano_id")
        ]

    if args.candidate_rank == "all":
        rows = all_rows
    else:
        rows = [row for row in all_rows if row.get("candidate_rank") == args.candidate_rank]

    if args.limit > 0:
        rows = rows[: args.limit]

    route_headings = build_route_headings(all_rows)
    output_metadata = args.output_dir / "downloaded_static_metadata.csv"
    output_rows: list[dict[str, str]] = []

    for i, row in enumerate(rows):
        source_index = row["source_index"]
        candidate_rank = row["candidate_rank"]
        pano_id = row["historical_pano_id"]
        date = row["historical_date"] or "unknown"
        heading = 0
        if args.heading_source == "route":
            heading = route_headings.get(source_index, 0)
        elif args.heading_source == "historical" and row.get("heading"):
            heading = int(float(row["heading"]))

        filename = f"source_{int(source_index):04d}_rank_{candidate_rank}_{date}_heading_{heading:03d}_{pano_id}.jpg"
        image_dir = args.output_dir if args.flat else args.output_dir / date
        image_dir.mkdir(parents=True, exist_ok=True)
        image_path = image_dir / filename

        print(
            f"[{i + 1}/{len(rows)}] source={source_index} "
            f"rank={candidate_rank} date={date} pano={pano_id} heading={heading}"
        )

        status = "ok"
        error = ""
        try:
            image = get_streetview(
                pano_id=pano_id,
                api_key=api_key,
                width=args.width,
                height=args.height,
                heading=heading,
                fov=args.fov,
                pitch=args.pitch,
            )
            image.save(image_path, "jpeg", quality=92)
        except Exception as exc:
            status = "error"
            error = f"{type(exc).__name__}: {exc}"
            print(f"Download failed: {error}")

        output_row = dict(row)
        output_row["static_image_path"] = str(image_path) if status == "ok" else ""
        output_row["static_heading"] = str(heading)
        output_row["heading_source"] = args.heading_source
        output_row["download_status"] = status
        output_row["download_error"] = error
        output_rows.append(output_row)
        time.sleep(args.sleep)

    if output_rows:
        fieldnames = list(output_rows[0].keys())
        with output_metadata.open("w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(output_rows)

    ok_count = sum(1 for row in output_rows if row["download_status"] == "ok")
    err_count = sum(1 for row in output_rows if row["download_status"] == "error")
    print(f"Images directory: {args.output_dir}")
    print(f"Metadata: {output_metadata}")
    print(f"Downloaded rows: {len(output_rows)} | ok={ok_count} errors={err_count}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
